import React from "react";
import Head from "next/head";
import styles from "./MainLayout.module.css";

function MainLayout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>First App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>{children}</main>
    </div>
  );
}

export default MainLayout;
